apiVersion: "networking.k8s.io/v1beta1"
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: "/"
        pathType: "Prefix"
        backend:
          serviceName: "monitoring-grafana"
          servicePort: 80
