
apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: monitoring-loki-nodeport
spec:
  type: NodePort
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
    nodePort: 30001
  selector:
    app: loki
    release: {{ .Release.Name }}

